### ISSUE TITLE
QoL changes that TrenchBroom needs

### ISSUE THREAD

**Issue by rtxa** [rtxa/TrenchBroom#23]
#### Texture alignment
- [ ] Allow to align multiple faces in UV tool. This would improve its usability if we can align multiple faces which are coplanar or adjacent. "Treat as one" button could be added.
  - https://github.com/TrenchBroom/TrenchBroom/issues/837
  - https://github.com/TrenchBroom/TrenchBroom/issues/3683
- [ ] Add a button to maximize or open in another windows the UV texture alignment tool. This would help with bigger shapes or textures, considering UI is too crowed and small.
- [ ] Add justify tools like Center, Fit, Left, Right, etc. like J.A.C.K. does. https://github.com/TrenchBroom/TrenchBroom/pull/3932

#### Face tool
- [ ] Add a button to open another window for the texture browser or maximize. Isn't easy to look for textures like J.A.C.K/Hammer does.
- [ ] Allow to select what texture collection/wad to show. This helps if texture packs have a lot of files. Disabling collections is not a good workaround.
- [ ] Allow to rename textures in the Face tool. This would allow to fix maps with missing textures by renaming it to the correct ones. Only workaround is to open the map in J.A.C.K/Hammer.
- [ ] #24

#### General UI
- [ ] https://github.com/TrenchBroom/TrenchBroom/issues/3973. TB UI is too crowded and would benefit that some sections have their own windows/sidebar. [DarkRadiant approach](https://github.com/user-attachments/assets/58bb1cac-1077-42e4-81bf-b505a6c63f4f) with horizontal tabs sections, we could have one vertical for Entity browser and horizontal for Texture browser.
- [ ] Add icons by FGD key property name to improve visualization. https://github.com/TrenchBroom/TrenchBroom/issues/4347
- [ ] Add option to display models or entities bounding box in Wireframe mode. This is because they hide what is behind them, making them a hassle for side-views if you come from working in Hammer/J.A.C.K.

#### Layer system
- [ ] Show what brushes/entities are inside and not just a count. This is helpful if we have many entities or there are hidden ones. A search bar could help. We can display what name it has by his targetname. https://github.com/TrenchBroom/TrenchBroom/issues/3403

#### FGD system
- [ ] Better support for FGD properties:
  - https://github.com/TrenchBroom/TrenchBroom/issues/4293. Useful discussion on how to make properties more generic.
  - https://github.com/TrenchBroom/TrenchBroom/pull/4617. This removes hardcoding of target_name/target_source. Useful for other engines.
  
#### 3D view
- [ ] Make alpha-blending for faces the default instead of just discarding pixels if their alpha value is < 0.5 (Alpha-test). This would solve transparency issues with TGA textures, HL sprites, etc. Quake textures already have the transparency set in their palette so they wouldn't be affected. Finishing the material system would be better but this would do for now.
- [ ] Allow to replace with custom texture if flag attribute is set. For example, if Sky attribute is set, replace any brush faces texture with a sky texture, if it's clip, the same, etc. This would make more useful the 'transparent' attribute which alpha value is hardcoded to differentia from brush with transparency values.
